version: '3'

tasks:
  test:
    cmds:
      - task: run
        vars:
          CLI_ARGS: pytest

  build:
    dir: env/
    cmds:
      - docker compose build


  format:
    dir: env/
    cmds:
      - docker compose run --rm dev black .

  run: # Run a command in the development environment
    dir: env/
    cmds:
      - docker compose run --rm dev {{.CLI_ARGS}}