name: Unit Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: ./ci_bootstrap.sh

    - name: Run tests
      run: task test
